### ISSUE TITLE
Can file descriptors from `rina_open` or `rina_flow_alloc` be reassigned using `dup2`?

### ISSUE THREAD

**Issue by mirw** [vmaffione/rlite#17]
https://github.com/matt-williams/rina-interposer tries to map BSD sockets API to RINA.

Since when a socket is opened, rina-interposer doesn't know whether the socket will end up being used for a RINA-based connection (e.g. because this could depend on the parameters to `bind` or `connect`), rina-interposer maps `socket` calls straight through to BSD Sockets `socket` (not for example `rina_open`).  Later, when rina-interposer determines whether this socket should use RINA or not, rina-interposer then tries to use `dup2` to remap the original `socket`-provided file descriptor to the new RINA-provided file descriptor.  This succeeds.

However, when I subsequently passed this FD to `select`, it always returned success and calls to `rina_flow_accept` failed.  Does `dup2` work for file descriptors returned by `rina_open` or `rina_flow_alloc`?

It appears not, but my RINA setup wasn't very stable (trying to use shim-udp4), so I'm happy to be told "yes it does"!

**Comment by vmaffione** [comment]
You can use `dup()` or `dup2()` on file descriptors returned by `rina_open` and `rina_flow_accept`, as `dup` and `dup2` are system calls that work on any file descriptors.
However, you are not allowed to use socket calls (e.g. `accept`, `connect`, `bind`) on RINA file descriptors, as the corresponding kernel object is not a socket, but is a character device (e.g. like a serial port).

**Comment by vmaffione** [comment]
However, I don't understand you question. `dup` and `dup2` just duplicate a file descriptor, they don't remap anything as far as I know.

**Comment by mirw** [comment]
Thanks for your response!  A bit more detail on my use case...

I was trying to write a BSD-sockets-to-RINA mapping layer (https://github.com/matt-williams/rina-interposer) to make processes written for BSD sockets (and TCP/IP) run over RINA without recompilation.

*   When the process calls `socket`, my interposer calls through to the standard `socket` function, which creates a file descriptor mapping to a BSD (not RINA) socket - let's call it *x*.

*   When the process calls `listen`, my interposer works out the RINA connection details and calls `rina_open` and `rina_register`.  Unfortunately, `rina_open` returns a new file descriptor (*y*) from the one that was passed in (*x*), so I use `dup2` to clone the RINA-provided file descriptor over the top of the original BSD-sockets-provided-one, leaving the original process none the wiser - it can continue to use *x*, although it should now refer to the RINA-provided file descriptor.

*   Via `strace`, I can see that the process then calls `select` on file descriptor *x*, which returns immediately (even though should have been no flow to accept yet).

*   The process then calls `accept`, which my interposer again catches and remaps to `rina_flow_accept`.  However, this failed.

Unfortunately, I don't still have the deployment set up, so I'm not sure what else to provide - there's probably nothing else to investigate here.

**Comment by vmaffione** [comment]
Hi,
  I'm not sure that this can work, but let's try to see if it makes sense.
The `dup` or `dup2` just creates another file descriptor (say 4) referring to the same kernel object that an already open file descriptor (say 1) already refers to. This is used from the shell to "remap" stdin, stdout and/or stderr onto sockets or other kernel objects. You may want to have a look at this shell use case to understand what it should be done (it's a very popular "design pattern").

But this requires to close the original file descriptor (e.g. stdout) to reopen it. From your description, it doesn't seem you close the original file descriptor (e.g. the socket in your case). As a result, you end up calling `rina_flow_accept` on a file descriptor referring to a socket (and not to a RINA device). This clearly leads to a failure.

**Comment by vmaffione** [comment]
If you want an easy deployment, just look at Tutorial 5.2.

**Comment by vmaffione** [comment]
Hi, please just ignore my long message above, I misunderstood, sorry. I'll have a look at your code and get back to you asap.

**Comment by mirw** [comment]
No problem - I suspect I might have got the `dup2` parameters the wrong way round.  I'll try to find some time to try again.

(We were trying to use shim-udp4 as described in tutorial 5.2 over the weekend, but unfortunately hit https://github.com/vmaffione/rlite/issues/18.)

**Comment by vmaffione** [comment]
Ok, regarding #18 it may be a simple misconfiguration, as it works ok to me. We can figure it out together.
