### ISSUE TITLE
Unregistering ipcp: confusing log message

### ISSUE THREAD

**Issue by MCapitani** [vmaffione/rlite#52]
It seems like this might be a typo.

When unregistering a normal DIF IPCP from a shim DIF (in my case it was a shim-wifi) the uipcps logs report
```
[10:03:35:DBG][ny.IPCP]register_to_lower_one: IPCP name n.DIF registered into DIF rinawlanpwd.DIF
[10:03:35:DBG][ny.IPCP]register_to_lower_one: DAF name n.DIF registered into DIF rinawlanpwd.DIF for broadcast enrollment
```
which seems to be the opposite of what was requested.
However, the command seems to work correctly and in the kernel logs the unregistration is correctly reported.

The exact command used is `sudo rlite-ctl ipcp-unregister ny.IPCP rinawlanpwd.DIF`.

**Comment by vmaffione** [comment]
Thanks for spotting this. Yes, the code does the right thing, as you can inspect with regs-show, or also with dif-rib-show in case of registrations or unregistrations to normal DIFS. However, the same functions handle both registrations and unregistrations, so I forgot to change the logs depending of the actual operations performed. I will fix it in a while
