### ISSUE TITLE
rina_register() : No such device or address

### ISSUE THREAD

**Issue by masonticehurst** [vmaffione/rlite#96]
Hi all,

We are conducting some undergraduate research on RINA and have been using rLite's fantastic documentation and implementation to learn more about the architecture. We did notice one recurring issue when trying to interface using the rLite API as well as when trying to use the integrated rinacat tool.

Using the latest master branch, running the following causes this error:
```
$ sudo rlite-ctl ipcp-create e1.IPCP shim-eth e.DIF
write(ctrlmsg): No such device or address
```

In addition to this, attempting to call rina_register() from the C API raises an equivalent exception.
Am I doing something wrong here? Any pointers to get these functional would be much appreciated. Thanks.

System configuration:
OS: Ubuntu 20.04.6 LTS x86_64 
Host: VirtualBox 1.2 
Kernel: 5.15.0-84-generic 
Shell: bash 5.0.17 
CPU: Intel i9-9900K (8) @ 3.600GHz 
GPU: 00:02.0 VMware SVGA II Adapter 
Memory: 4656MiB / 15988MiB

**Comment by gravity64** [comment]
Hi,
 First, I did a commit to upgrade to the latest protobuf and cmake. Please recompile from current master.
On my Ubuntu 20.04.6 LTS version I do not experience your issue.

Did you load the necessary kernel modules?
````
# modprobe rlite
# modprobe rlite-shim-eth
# modprobe rlite-normal
````

?

**Comment by masonticehurst** [comment]
> ?

Hi there, and thanks for your reply. I did indeed made sure that the necessary kernel modules are loaded via lsmod. Interestingly, after pulling the latest changes and building rLite again, it seems to now be registering without hiccup!
The rinacat tool is now working as expected :)

Thank you for your help.
